name = "bukuku"
compatibility_date = "2024-02-10"
pages_build_output_dir = "dist"

# Konfigurasi Database D1
[[d1_databases]]
binding = "DB"
database_name = "bukuku"
database_id = "81676e9f-fec8-4e3b-bc9a-0296d8c08617"

# Variabel Environment Lokal (Untuk development)
# Untuk production, set langsung di Dashboard Cloudflare > Settings
[vars]
JWT_SECRET = "rahasia-lokal-12345"
