name = "bukuku"
compatibility_date = "2024-02-10"
pages_build_output_dir = "dist"

# Konfigurasi Database D1
[[d1_databases]]
binding = "DB"
database_name = "bukuku-db"
database_id = "MASUKKAN_ID_DATABASE_D1_ANDA_DISINI"

# Variabel Environment Lokal (Untuk development)
# Untuk production, set langsung di Dashboard Cloudflare > Settings
[vars]
JWT_SECRET = "rahasia-lokal-12345"
